version: '3'
services:
  oyez:
    image: cal:base
    privileged: true
    restart: always
    container_name: oyez
    depends_on:
      - sengee
    environment:
      - LC_ALL=zh_CN.UTF-8
      - LANGUAGE=zh_CN.UTF-8
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - ./app/oyez:/home/datayoo/app/oyez
      - ./app/lib:/home/datayoo/app/oyez/lib
      - ./app/oyez/scripts:/home/datayoo/scripts
      - ./operators:/home/datayoo/app/oyez/oyezlet/operators
      - ./dfs:/home/datayoo/dfs
  nginx:
    image: nginx:alpine
    privileged: true
    restart: always
    container_name: nginx
    depends_on:
      - sengee
      - brackets
      - authx
    ports:
      - 38172:38172
    volumes:
      - ./nginx/conf/all_http_38172.conf:/etc/nginx/conf.d/sengee.conf
      - ./nginx/ui:/home/datayoo/ui
  sengee:
    image: server:base
    privileged: true
    restart: always
    container_name: sengee
    expose:
      - "38500"
      - "8823"
    ports:
      - 38502:38502
    depends_on:
      - mysql
    volumes:
      - ./app/sengee:/home/datayoo/app/sengee
      - ./app/lib:/home/datayoo/app/sengee/lib
      - ./app/sengee/scripts:/home/datayoo/scripts
      - ./operators:/home/datayoo/app/sengee/operators/
      - ./upload:/home/datayoo/app/sengee/upload
      - ./dfs:/home/datayoo/dfs
    hostname: datayoo.sengee
  brackets:
    image: server:base
    privileged: true
    restart: always
    container_name: brackets
    expose:
      - "38600"
    ports:
      - 8989:8989
    depends_on:
      - authx
      - mysql
    volumes:
      - ./app/brackets:/home/datayoo/app/brackets
      - ./app/lib:/home/datayoo/app/brackets/lib
      - ./app/brackets/scripts:/home/datayoo/scripts
      - ./dfs:/home/datayoo/dfs
    hostname: datayoo.brackets
  authx:
    image: server:base
    privileged: true
    restart: always
    container_name: authx
    expose:
      - "38700"
    ports:
      - 38702:38702
    depends_on:
      - mysql
    volumes:
      - ./app/authx:/home/datayoo/app/authx
      - ./app/lib:/home/datayoo/app/authx/lib
      - ./app/authx/scripts:/home/datayoo/scripts
    hostname: datayoo.authx
  mysql:
    restart: always
    privileged: true
    image: mysql:8.0.27
    container_name: mysql
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init/initDb.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --authentication_policy=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "datayoo@123"
      TZ: "Asia/Shanghai"
    expose:
      - "3306"
    ports:
      - 53306:3306
    hostname: datayoo.mysql
